config/routes.rb
Scouter::Application.routes.draw do
  root to: 'repositories#index'

  resources :repositories, only: [:index, :show, :destroy, :create]
  resources :builds, only: [:new, :create, :show, :index]

  get "class_details/show/:id" => "class_details#show", as: :class_detail

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/build.rb
class Build < ActiveRecord::Base
  include AASM

  belongs_to :repository
  has_many :klasses, dependent: :destroy

  aasm do
    state :scheduled, initial: true
    state :running,   enter: :analyze
    state :completed

    event :run do
      transitions from: :scheduled, to: :running
    end

    event :complete do
      transitions from: :running, to: :completed
    end
  end

  def analyze
    processor = Processor.new
    processor.process repository.clone_url

    self.klasses = processor.class_details.map do |detail|
      Klass.new(detail)
    end
    complete!
  end
  handle_asynchronously :analyze
end

app/models/class_detail.rb
class ClassDetail < ActiveRecord::Base
  belongs_to :repository
  validates_presence_of :class_name, :score

  def to_s
    class_name
  end

  def grade
    case method_average
    when 0...10.1
      :great
    when 10.1...20.1
      :good
    when 20.1...40.1
      :normal
    when 40.1...60.1
      :poor
    when 60.1...100.1
      :bad
    when 100.1..200
      :terrible
    else
      :crap
    end
  end
end

app/models/klass.rb
class Klass < ActiveRecord::Base
  belongs_to :build
  validates_presence_of :name, :score

  def to_s
    name
  end

  def grade
    case method_average
    when 0...10.1
      :great
    when 10.1...20.1
      :good
    when 20.1...40.1
      :normal
    when 40.1...60.1
      :poor
    when 60.1...100.1
      :bad
    when 100.1..200
      :terrible
    else
      :crap
    end
  end
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  has_many :builds, dependent: :destroy

  validates_uniqueness_of :name, message: "This repository already exists"
  validates_format_of :name, with: %r{\A[\w-]+/[\w-]+\z}

  def create_build
    build = builds.new
    build.run! if build.save
  end

  def klasses
    current_build.try(:klasses) || []
  end

  def clone_url
    "#{github_url}.git"
  end

  def github_url
    "https://github.com/#{name}"
  end

  def current_build
    self.builds.last
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.github_username = auth["info"]["nickname"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    current_user.present?
  end

  helper_method :current_user, :user_signed_in?
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  # GET /builds
  def index
    @builds = Build.all
  end

  # GET /builds/1
  def show
    @build = Build.find(params[:id])
  end

  # GET /builds/new
  def new
    @build = Build.new
  end

  # POST /builds
  def create
    @build = Build.new(build_params)

    respond_to do |format|
      if @build.save
        format.html { redirect_to @build, notice: 'Build was successfully created.' }
      else
        format.html { render 'new' }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.require(:build).permit(:repository_id, :state)
    end
end

app/controllers/class_details_controller.rb
class ClassDetailsController < ApplicationController
  def show
    @class_detail = ClassDetail.find params[:id]
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  def show
    @repository = Repository.find params[:id]
    @classes    = @repository.klasses
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: "Repository not found"
  end

  def create
    @repository = Repository.new repository_params
    respond_to do |format|
      if @repository.save
        @repository.create_build
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
      else
        format.html { render 'new' }
      end
    end
   end

  def new
    @repository = Repository.new
  end

  def index
    # @repositories = Repository.all
    client = Octokit::Client.new \
      client_id: ENV['GITHUB_CLIENT_ID'],
      client_secret: ENV['GITHUB_CLIENT_SECRET']
    @repositories = client.repositories(current_user.github_username)
  end

  private
  def repository_params
    params.require(:repository).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format number
    "%.2f" % number
  end
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/class_details_helper.rb
module ClassDetailsHelper
end

app/helpers/repository_helper.rb
module RepositoryHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/builds/_form.html.haml
= simple_form_for(@build) do |f|
  = f.error_notification

  .form-inputs
    = f.association :repository
    = f.input :state

  .form-actions
    = f.button :submit

app/views/builds/edit.html.haml
%h1 Editing build

= render 'form'

= link_to 'Show', @build
\|
= link_to 'Back', builds_path

app/views/builds/index.html.haml
%h1 Listing builds

%table
  %tr
    %th Repository
    %th State
    %th
    %th
    %th

  - @builds.each do |build|
    %tr
      %td= build.repository
      %td= build.state
      %td= link_to 'Show', build
      %td= link_to 'Edit', edit_build_path(build)
      %td= link_to 'Destroy', build, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Build', new_build_path

app/views/builds/new.html.haml
%h1 New build

= render 'form'

= link_to 'Back', builds_path

app/views/builds/show.html.haml
%p#notice= notice

%p
  %b Repository:
  = @build.repository
%p
  %b State:
  = @build.state

= link_to 'Edit', edit_build_path(@build)
\|
= link_to 'Back', builds_path

app/views/class_details/show.html.haml
.well
  .row
    %h2= @class_detail.class_name
    %hr/
    .col-md-2
      %h3= @class_detail.grade
    .col-md-10
      %p
        =format @class_detail.score
        %strong Score
      %p
        =format @class_detail.method_average
        %strong Average Score/Method
      %p
        =@class_detail.method_count
        %strong Methods

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scouter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <%= link_to "Scouter", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "Repositories", repositories_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li>
                <p class="navbar-text">Signed in as <%= current_user.name %>!</p>
              </li>
              <li>
                <%= link_to "Sign out", signout_path %>
              </li>
            <% else %>
              <li>
                <%= link_to "Sign in with GitHub","/auth/github" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, class: "alert alert-#{name}" do %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= msg %>
        <% end %>
      <% end %>
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/repositories/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Repositories
  %tbody
    - @repositories.each do |repository|
      %tr
        %td= link_to repository.name, "repository"

app/views/repositories/new.html.haml
= link_to 'Back', :back
= simple_form_for(@repository, defaults: { wrapper_html: {class: 'form-group'}, input_html: { class: 'form-control' }}) do |f|
  = f.input :name, label: "Repository location"
  = f.submit class: "btn btn-default"

app/views/repositories/show.html.haml
%h2.repo-name
  = @repository.name
  = link_to @repository.github_url, target: "_blank" do
    .github-logo
%hr/
- if @repository.current_build.completed?
  %table.table.table-striped.table-bordered
    %thead
      %tr
        %th.col-md-1.center Grade
        %th Class
    %tbody
      - @classes.each do |klass|
        %tr
          %td.center= image_tag "#{klass.grade}-mini.png"
          %td= klass.name
- else
  %p Processing ...